apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-ecommerce
spec:
  selector:
    matchLabels:
      app:  django-ecommerce
  template:
    metadata:
      labels:
        app:  django-ecommerce
    spec:
      containers:
      - name:  django-ecommerce
        image: matheusnicolay/netflix-clone-react-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
