apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ecommerce-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - ecommerce.nmatheus.cloud
      secretName: django-ecommerce-tls
  rules:
  - host: ecommerce.nmatheus.cloud
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: django-ecommerce
              port:
                number: 80
