name: CI/CD

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4.1.1 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./netflix-clone-react-app
        file: netflix-clone-react-app/Dockerfile
        push: true
        tags: |
          matheusnicolay/netflix-clone-react-app:${{ github.run_number }}
          matheusnicolay/netflix-clone-react-app:latest

  CD:
     runs-on: ubuntu-latest
     needs: [CI]
     steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.1 
      - name: Configurar Credenciais AWS 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Configurar o kubeConfig
        run: aws eks update-kubeconfig --name eks-netflixclone --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./kubernetes/
            https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.2/deploy/static/provider/cloud/deploy.yaml
          images: |
            matheusnicolay/netflix-clone-react-app:${{ github.run_number }}